name: Production Deploy 

on:
  workflow_run:
    workflows: ["Web Sanity Test Linting"]
    branches: [master]
    types:
     - completed

jobs:
  deploy:
    # only deploy if the previous workflow was a success 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # run on ubuntu container
    runs-on: ubuntu-latest

    steps:
    # grab the repo
    - uses: actions/checkout@v2
    - name: Rsync Deploy
      env:
        # define SSH/Rsync destination environment var
        dest: '<<USER>>@<<SERVER>>:/srv/<<PATH>>'
      run: |
        echo "${{secrets.DEPLOY_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chrlvzi --delete \
          -e 'ssh -i ./deploy_key -p 22 -o StrictHostKeyChecking=no' \
          --exclude '/deploy_key' \
          --exclude '/.*/' \
          --exclude '.*' \
          --exclude '/cgi-bin/' \
          --exclude 'README.md' \
          ./ ${{env.dest}}